- hosts: ubuntu
  become: yes
  tasks:

    - name: update
      apt: update_cache=yes

    - name: Install Apache
      apt: name=apache2 state=latest 

    - name: Change Apache port 
      lineinfile:
            path: /etc/apache2/ports.conf
            state: present
            regexp: 'Listen 80'
            line: "Listen 8080"
      notify:
        - restart-apache

  handlers:
    - name: restart-apache
      service: name=apache2 state=restarted
