- hosts: ubuntu
  become: yes
  tasks:

    - name: update
      apt: update_cache=yes

    - name: Install Bind
      apt: name=bind9 state=latest

  handlers:
    - name: restart bind
      service: name=bind9 state=restarted

