---

- hosts: servers
  become: yes

  vars:
          zabbix_server: 178.154.203.19
          centos_link: http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm
          ubuntu_link: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
          ubuntu_file: zabbix-release_5.0-1+focal_all.deb

  tasks:
          ### INSTALL on CENTOS ###
  - name: install zabbix CentOS rpm file
    yum:
            name: "{{ centos_link }}"
    when: ansible_os_family == "RedHat"

  - name: install zabbix-agent for CentOS
    yum:
            name: zabbix-agent
            enablerepo: zabbix
            update_cache: true
            state: present
    when: ansible_os_family == "RedHat"

    ### INSTALL ON UBUNTU ###

  - name: install zabbix Ubuntu deb file
    get_url:
            url: "{{ ubuntu_link }}"
            dest: "/tmp/{{ ubuntu_file }}"
    when: ansible_os_family == "Debian"

  - name: install zabbix deb for Ubuntu
    apt:
            deb= "/tmp/{{ ubuntu_file }}"
    when: ansible_os_family == "Debian"

  - name: install zabbix-agent for Ubuntu 
    apt:
            name: zabbix-agent
            state: latest
    when: ansible_os_family == "Debian"

    ### CONFIGURATION ###
  - name: enable zabbix-server service
    systemd:
            name: zabbix-agent
            enabled: yes
            masked: no
    become: yes
 
  - name: make sure a service is stopped
    systemd: state=stopped name=zabbix-agent
    become: yes

  - name: mkdir /etc/zabbix/scripts and change rights
    file:
            path: /etc/zabbix/scripts
            state: directory
            owner: zabbix
            group: zabbix
            mode: 0700
    become: yes

# change zabbix agent config
  - name: change zabbix_agentd.conf Hostname
    lineinfile:
            path: /etc/zabbix/zabbix_agentd.conf
            state: present
            regexp: 'Hostname=Zabbix server'
            line: "Hostname={{ ansible_hostname }}"
    become: yes
    
  - name: change zabbix_agentd.conf ServerActive
    lineinfile:
            path: /etc/zabbix/zabbix_agentd.conf
            state: present
            regexp: 'ServerActive=127.0.0.1'
            line: "ServerActive={{ zabbix_server }}"
    become: yes

  - name: change zabbix_agentd.conf Server
    lineinfile:
            path: /etc/zabbix/zabbix_agentd.conf
            state: present
            regexp: 'Server=127.0.0.1'
            line: "Server={{ zabbix_server }}"
    become: yes

  - name: change zabbix_agentd.conf EnableRemoteCommands
    lineinfile:
            path: /etc/zabbix/zabbix_agentd.conf
            state: present
            regexp: '# EnableRemoteCommands=0'
            line: 'EnableRemoteCommands=1'
    become: yes

  - name: change zabbix_agentd.conf LogRemoteCommands
    lineinfile:
            path: /etc/zabbix/zabbix_agentd.conf
            state: present
            regexp: '# LogRemoteCommands=0'
            line: 'LogRemoteCommands=1'
    become: yes

  - name: start service
    systemd: state=started name=zabbix-agent
    become: yes

  handlers:
  - name: start zabbix-agent
    systemd:
            name: zabbix-agent 
            state: started 
            enabled: yes
            become: yes
