---

- hosts: centos

  become: yes

tasks:
  - name: install zabbix centOS 7 rpm file
  yum:
    name: https://repo.zabbix.com/zabbix/4.4/rhel/7/x86_64/zabbix-release-4.4-1.el7.noarch.rpm
  when: ansible_os_family == "RedHat"

  - name: install zabbix-agent 4.4 for centOS 7
  yum: 
    name: zabbix-agent
    enablerepo: zabbix
    update_cache: true
    state: latest
  when: ansible_os_family == "RedHat" 



  handlers:

  - name: Start zabbix-agent

    service: name=zabbix-agent state=started enabled=yes
